### ISSUE TITLE
the question about the paper in IV-A

### ISSUE THREAD

**Issue by hanm2019** [horizon-research/Efficient-Deep-Learning-for-Point-Clouds#13]
hello, I was really impressed on the idea of delayed-aggregation, and the experiment seem the module accuracy suffer only a litter effect, but reduce a lot of calculation work, cool!
but I also confuse about the   Equ.3, and I can't deducing it. could you help me?

e.g.
```
φ(φ(5-6)*4)*3) = 0
φ(φ(5)*4)*3) - φ(φ(6)*4)*3) =  - 12
```

i think maybe 
`φ(φ(P-Pi)*w1)*w2) =  φ { φ(φ(P)*w1)*w2)- φ(φ(Pi)*w1)*w2)} `
make more sense.

**Comment by YuFengUofR** [comment]
φ stands for multiple MLP with Relu, sometimes with a Maxpool at the end.

**Comment by hanm2019** [comment]
Thanks for your reply:)
maybe my example is not appropriate，when φ stands for multiple MLP with Relu, I still can't deducing it. 
could you give me some inspire.

**Comment by YuFengUofR** [comment]
it is approximation not 100% equal

**Comment by hanm2019** [comment]
thanks~
